### PR TITLE
Use methods when there is state. Removed dead code. Default to not export.

### PR DESCRIPTION
**Pull request by ojongerius**
There is a fair amount of getting both values and errors, followed by passing those values to another function.

While going through the code I stumbled on some dead code, which I removed. I also moved the zone helper function out of main (as you planned on doing), and renamed functions that were not used outside of the package to not be exported.

### CODE REVIEW

**Comment by ojongerius** [comment]
Some extra context/information: I've mainly opened this PR for discussion.

Tests pass but I've not ran any integration tests.

**Comment by wolfeidau** [comment]
Really need to break this into pieces, it is really hard for me to review in it's current state.

* Yes the `ds` stuff was a bit of experiment and needs a cleanup, happy to accept that and merge with gusto.
* On the private stuff, I plan to use these methods in part or full in other tools, hence me keeping most stuff public. A few methods need to be rejigged like that version related one.
* Zone helper move is welcome
* Lastly you need to be careful around http://dave.cheney.net/2016/03/19/should-methods-be-declared-on-t-or-t 

Again i would love it if you could break these up.

**Comment by ojongerius** [comment]
Cool. this was me being stuck in an airplane and getting a little carried away.

I'll break this up into a few PRs so it's a little more manageable.

**Comment by wolfeidau** [comment]
@ojongerius no problem at all, totally understand the feeling.

I was tempted to cherry pick but would prefer you just undid the commits and broke it up into bite size chunks to preserve your contributions.

Thanks again.

**Pull request closed without merging**
