### PR TITLE
Support JSON output.

### PR DESCRIPTION
**Pull request by ojongerius**
This add support for JSON output. It does not add support for JSON output in TableWriter. If you are interested I can take a look at included this.

### CODE REVIEW

**Comment by wolfeidau** [comment]
I think this could be a little confusing for people without the JSON output of the table.

I do totally agree it would be great to have all commands outputting JSON.

I want to hide the table writer, and all the console output things behind an interface, with a couple of implementations.

**Comment by ojongerius** [comment]
Sure, that makes sense, let's see if I can refactor this to your liking.

**Comment by ojongerius** [comment]
It's been a month and don't have time nor direct need for this at the moment. Closing.

**Comment by wolfeidau** [comment]
Going to merge this now then.

Cheers for your work so far.

**Pull request merged**
